Map<String, String> strings = {
  "discover": "Discover",
  "drinks": "Drinks",
  "collection": "Collection",
  "header_discover": "Raise Your Glass to Our Handpicked Drink!",
  "header_drinks": "Get Ready to Sip and Discover Your Next Cocktail!",
  "header_collection_p1": "Happy Hour a Collection of ",
  "header_collection_p2": " Drinks!",
  "glass_cocktail": "Cocktail Glass",
  "glass_champagne": "Champagne Flute",
  "empty_list": "No Drinks Found",
  "alcoholic": "Alcoholic",
  "non_alcoholic":"Non Alcoholic",
  "optional_alcoholic":"Optional Alcohol",
  "search_drink": "Search for a drink",
  "ingredients": "Ingredients",
};
